import Box from "@mui/material/Box";
import Navbar from "../components/Navbar";
import { AuthProvider } from "./Providers";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';



export const metadata = {
	title: "Clients Database",
	description: "Generated by Lemine M.",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<AppRouterCacheProvider>
						<Navbar />
						<Box sx={{ mt: 10 }}>
							{children}
						</Box>
					</AppRouterCacheProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
